apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routing-service
  labels:
    app: routing-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
      - name: routing-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "{{ .Values.service.port }}"
        - name: DB_TRIPDSN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-routing-service-secrets
              key: trip_dsn
        - name: KAFKA_BROKERS
          value: "{{ .Values.kafka.brokers | join \",\" }}"
        - name: KAFKA_TIMEOUT
          value: "{{ .Values.kafka.timeout }}"
        - name: KAFKA_GROUPID
          value: "{{ .Values.kafka.groupId }}"
        - name: KAFKA_CONSUMETOPICS
          value: "{{ .Values.kafka.consumeTopics | join \",\" }}"
        - name: KAFKA_PRODUCETOPIC
          value: "{{ .Values.kafka.produceTopic }}"
        - name: OTLP_ENDPOINT
          value: "{{ .Values.otlp.endpoint }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
        resources:
{{ toYaml .Values.resources | indent 10 }}
