apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-routing-service-secrets
type: Opaque
stringData:
  trip_dsn: {{ .Values.secrets.tripDsn | quote }}
  ref_dsn: {{ .Values.secrets.refDsn | quote }}

