apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routing-service
  labels:
    app: routing-service
spec:
  type: ClusterIP
  selector:
    app: routing-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8081
    protocol: TCP
    name: http

