apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-operator-api-secrets
type: Opaque
stringData:
  operator_dsn: "{{ .Values.secrets.operatorDsn }}"
  trip_dsn: "{{ .Values.secrets.tripDsn }}"
  batch_dsn: "{{ .Values.secrets.batchDsn }}"
  auth_hs256secret: "{{ .Values.secrets.authHs256Secret }}"
  tls.crt: "{{ .Values.secrets.refMtls.tlsCrt }}"
  tls.key: "{{ .Values.secrets.refMtls.tlsKey }}"
  ca.crt: "{{ .Values.secrets.refMtls.caCrt }}"
