apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-operator-api-secrets
type: Opaque
stringData:
  operator_dsn: "{{ .Values.secrets.operatorDsn }}"
  auth_hs256secret: "{{ .Values.secrets.authHs256Secret }}"
