apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-operator-api
  labels:
    app: operator-api
spec:
  type: ClusterIP
  selector:
    app: operator-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8090
    protocol: TCP
    name: http

