apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reference-service-secrets
type: Opaque
stringData:
  auth_hs256secret: "{{ .Values.secrets.authHs256Secret }}"
  db_dsn: "{{ .Values.secrets.dbDsn }}"
