apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reference-service
  labels:
    app: reference-service
spec:
  type: ClusterIP
  selector:
    app: reference-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
