apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-batching-service
  labels:
    app: batching-service
spec:
  type: ClusterIP
  selector:
    app: batching-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8083
    protocol: TCP
    name: http

