grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: null
prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchNames:
        - default
