apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mobile-gateway-secrets
type: Opaque
stringData:
  db_dsn: {{ .Values.secrets.dbDsn | quote }}
  auth_secret: {{ .Values.secrets.authSecret | quote }}
  auth_issuer: {{ .Values.secrets.authIssuer | quote }}
  auth_audience: {{ .Values.secrets.authAudience | quote }}
