apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mobile-gateway
  labels:
    app: mobile-gateway
spec:
  type: ClusterIP
  selector:
    app: mobile-gateway
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8088
    protocol: TCP
    name: http
