apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tracking-service
  labels:
    app: tracking-service
spec:
  type: ClusterIP
  selector:
    app: tracking-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8087
    protocol: TCP
    name: http

