apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reassignment-service
  labels:
    app: reassignment-service
spec:
  type: ClusterIP
  selector:
    app: reassignment-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8082
    protocol: TCP
    name: http
